name: Deploy to Aliyun Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/OP-Abstract-Warehouse-Management-System
          git pull origin main
          docker-compose down
          docker-compose build
          docker-compose up -d
